# append()	Adds an element at the end of the list|l.append(7)
# clear()	Removes all the elements from the list|l.clear()
# copy()	Returns a copy of the list|j=l.copy()
# count()	Returns the number of elements with the specified value|print(l.count(2))|from collections import Counter -----print(Counter(l))
# extend()	Add the elements of a list (or any iterable), to the end of the current list|l.extend((123,3232))
# index()	Returns the index of the first element with the specified value#l.index(123)|
# insert()	Adds an element at the specified position|l.insert(4,123)
# pop()	Removes the element at the specified position#mention the element in as argument|l.pop()
# remove()	Removes the first item with the specified value|l.remove(123)
# reverse()	Reverses the order of the list|l.reverse()
# sort()	Sorts the list
#find->
import array
disp = lambda var:print(var)
ar1 = array.array('i',[1,23,4,853,4])
ar_ext = array.array('i',[8888,888,88,88])
#ar1 = ar.array('u',['Alen','arun','bijon','broln'])
disp(ar1)
print("inserting array :")
ar1.insert(3,5)
disp(ar1)
print("Appending value :")
ar1.append(1000)
disp(ar1)
print("first value :",ar1[0])
print("first value pos:",ar1.index(4))
print("last value :",ar1[-1])
print("last value pos :",ar1.index(ar1[-1]))
print('to list', list(ar1))
print('range of val : ',ar1[0::2])
ar1.reverse()
print('reverse array : ',ar1)
print('reverse array : ',ar1[::-1])
print('array length :',len(ar1))
print('count of 4 in array :',ar1.count(4))
ar1.remove(4)
print('remove element:',ar1)
ar1.pop(0)
print('Pop first index :',ar1)
ar1.extend(ar_ext)
print('extended array:',ar1)